name: CI
on:
  - push
  - pull_request
jobs:
  phpunit:
    name: Unit test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: shivammathur/setup-php@v1
        with:
          php-version: ${{matrix.php-version}}
          tools: composer
          coverage: xdebug2
      - run: composer update --optimize-autoloader
      - name: phpunit test
        env:
          XDEBUG_MODE: coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
      - uses: codecov/codecov-action@v1
  phpstan:
    name: phpstan analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.4"
          - "8.0"
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v1
        with:
          php-version: ${{matrix.php-version}}
          tools: composer
      - run: composer update --optimize-autoloader
      - name: phpstan analyze
        run: vendor/bin/phpstan analyze src
